name: il_mobile
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.7.3
  - async-timeout=3.0.1
  - attrs=20.3.0
  - blas=1.0
  - boto=2.49.0
  - boto3=1.16.39
  - botocore=1.19.39
  - brotlipy=0.7.0
  - ca-certificates=2020.12.8
  - cachetools=4.2.0
  - certifi=2020.12.5
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=3.3.1
  - cycler=0.10.0
  - dbus=1.13.18
  - docutils=0.15.2
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - gensim=3.8.0
  - glib=2.63.1
  - google-api-core=1.22.2
  - google-auth=1.24.0
  - google-cloud-core=1.5.0
  - google-cloud-storage=1.35.0
  - google-crc32c=1.1.0
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.52.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - jmespath=0.10.0
  - joblib=1.0.0
  - jpeg=9b
  - kiwisolver=1.3.0
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcrc32c=1.1.1
  - libcxx=10.0.1
  - libcxxabi=10.0.1
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - llvm-openmp=10.0.1
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - multidict=4.7.6
  - ncurses=6.2
  - numpy=1.19.1
  - olefile=0.46
  - openssl=1.1.1i
  - pandas=1.1.0
  - pcre=8.44
  - pip=20.1.1
  - protobuf=3.13.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.8
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.0
  - requests=2.25.1
  - rsa=4.6
  - s3transfer=0.3.3
  - scikit-learn=0.23.2
  - seaborn=0.11.1
  - setuptools=49.2.0
  - sip=4.19.8
  - six=1.15.0
  - smart_open=4.0.1
  - sqlite=3.32.3
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.54.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - decorator==4.4.2
    - future==0.18.2
    - imageio==2.9.0
    - networkx==2.5
    - pillow==7.2.0
    - pywavelets==1.1.1
    - scikit-image==0.18.0
    - scipy==1.5.4
    - tifffile==2020.12.8
    - torch==1.5.1
    - torchvision==0.6.1
